// <auto-generated />
namespace ABPProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ChangPurchase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangPurchase));
        
        string IMigrationMetadata.Id
        {
            get { return "201708170742561_ChangPurchase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
